/**
 * @param {Object} attributes - an object representing the attributes of one user
 * @return {Number} - a number between [0-1] generated by the scoring logic. 
 * Takes a list of attributes and generates a score based on the attributes. 
 */
const scoreLogic = (attributes) => {
    if (parseInt(attributes.spicyFoodTolerance) < 3) return 0;
    let aggregate = Object.values(attributes).reduce(
        (acc, currentValue) => acc + currentValue
    );
    aggregate /= 100;
    return aggregate;
};

export default scoreLogic;
